wandb_version: 1

model_path:
  desc: null
  value: ./Best_LA_model_for_DF.pth
num_epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 1.0e-06
weight_decay:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 14
data_dir_train:
  desc: null
  value: D:\programming\datasets\for-2seconds\training
data_dir_valid:
  desc: null
  value: D:\programming\datasets\for-2seconds\validation
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714563306.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      6: 4.39.3
      8:
      - 3
      - 5
      13: windows-amd64
